"""
Saskatchewan Archery Ranges Scraper
Uses crawl4ai to crawl club websites and compile data into a CSV.
"""
import asyncio
import csv
import json
import os
import sys

# crawl4ai imports
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig

# Known Saskatchewan archery clubs from SAA 2025 affiliated clubs list
# Pre-seeded with confirmed data from web research; crawl4ai enriches further
CLUBS = [
    {
        "post_title": "Frontier Bowmen Archery Club",
        "post_category": "Archery Club",
        "post_address": "2255 14th Avenue",
        "post_city": "Regina",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "S4P 0X9",
        "post_latitude": "50.4452",
        "post_longitude": "-104.6189",
        "phone": "",
        "email": "",
        "website": "https://frontierbowmen.com/",
        "post_content": "Frontier Bowmen is a well-established archery club in Regina offering both indoor and outdoor facilities. The indoor range is located at 2255 14th Avenue with 24/7 member access. The outdoor range at Botkin's Pits features field and 3D courses north of the city.",
        "post_tags": "indoor, outdoor, 3D, field, target, competitive",
        "business_hours": "24/7 member access (indoor restricted Tue/Wed 6-9PM during JOP season)",
        "facility_type": "Both",
        "has_pro_shop": "No",
        "has_3d_course": "Yes",
        "has_field_course": "Yes",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "Yes",
        "bow_types_allowed": "Recurve, Compound, Longbow, Crossbow",
    },
    {
        "post_title": "Wascana Archers",
        "post_category": "Archery Club",
        "post_address": "109 Hodsman Road",
        "post_city": "Regina",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "50.4300",
        "post_longitude": "-104.5900",
        "phone": "",
        "email": "",
        "website": "https://wascanaarchers.ca/",
        "post_content": "Wascana Archers is a nonprofit, 100% volunteer-operated archery club in the Regina area. They operate an indoor range at 109 Hodsman Road and a 60-acre outdoor range approximately 25 km north of Regina with 24/7 member access, trails, and open fields.",
        "post_tags": "indoor, outdoor, 3D, field, nonprofit",
        "business_hours": "24/7 member access",
        "facility_type": "Both",
        "has_pro_shop": "No",
        "has_3d_course": "Yes",
        "has_field_course": "Yes",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "No",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Saskatoon Straight Shooters Archery Club",
        "post_category": "Archery Club",
        "post_address": "Range Road 3050",
        "post_city": "Saskatoon",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "S7S 1N8",
        "post_latitude": "52.1332",
        "post_longitude": "-106.6700",
        "phone": "",
        "email": "",
        "website": "https://saskatoonarchery.com/",
        "post_content": "The Saskatoon Straight Shooters Archery Club is a family-friendly, inclusive club affiliated with the SAA. They use the Saskatoon Wildlife Federation's 7,000+ sq ft indoor range from October to April and an outdoor range at SWF from May onwards. They also have Tri-Club outdoor range access near Vanscoy.",
        "post_tags": "indoor, outdoor, target, youth, JOP",
        "business_hours": "Tuesdays (Club Night)",
        "facility_type": "Both",
        "has_pro_shop": "No",
        "has_3d_course": "No",
        "has_field_course": "No",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "Yes",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Bowbusters Archery Club",
        "post_category": "Archery Club",
        "post_address": "101 1st St W",
        "post_city": "Vanscoy",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "S0L 3J0",
        "post_latitude": "52.0200",
        "post_longitude": "-106.8600",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/people/Bowbusters-Archery-Club/100057474369199/",
        "post_content": "Bowbusters Archery Club in Vanscoy offers indoor and outdoor archery ranges with 24/7 access for members. Annual club membership is $175 plus a $50 SAA membership. Non-members may shoot as guests up to two times under SAA insurance rules.",
        "post_tags": "indoor, outdoor, 3D",
        "business_hours": "24/7 member access",
        "facility_type": "Both",
        "has_pro_shop": "No",
        "has_3d_course": "Yes",
        "has_field_course": "No",
        "membership_required": "Yes",
        "membership_price_adult": "$175/year (+ $50 SAA)",
        "equipment_rental_available": "No",
        "lessons_available": "No",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Battle River Archers",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Battleford",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "52.7578",
        "post_longitude": "-108.3150",
        "phone": "",
        "email": "",
        "website": "https://battleriverarchers.ca/",
        "post_content": "Battle River Archers is an active archery club based in Battleford, Saskatchewan. Adult members enjoy 24/7 range access. JOP and Intro to Archery programs run on Tuesdays 6-7:30 PM and Wednesdays 7-9 PM, during which the range is reserved for youth programming.",
        "post_tags": "indoor, outdoor, youth, JOP, competitive",
        "business_hours": "24/7 (restricted Tue 6-7:30PM, Wed 7-9PM for JOP)",
        "facility_type": "Indoor",
        "has_pro_shop": "No",
        "has_3d_course": "No",
        "has_field_course": "No",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "Yes",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Thunderhead Archers",
        "post_category": "Archery Club",
        "post_address": "East of Delisle off Highway 766",
        "post_city": "Delisle",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "51.9266",
        "post_longitude": "-107.0036",
        "phone": "306-493-7738",
        "email": "",
        "website": "https://www.thunderheadarchers.com/",
        "post_content": "Thunderhead Archers, established in 1988, operates both an indoor target range (November to April) and an outdoor range (May to October) near Delisle, Saskatchewan. The outdoor range is located east of Delisle off Highway 766.",
        "post_tags": "indoor, outdoor, target, seasonal",
        "business_hours": "Indoor: Nov-Apr; Outdoor: May-Oct",
        "facility_type": "Both",
        "has_pro_shop": "No",
        "has_3d_course": "No",
        "has_field_course": "No",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "No",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Thunder Creek Archery Club",
        "post_category": "Archery Club",
        "post_address": "1235 Main St N",
        "post_city": "Moose Jaw",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "S6H 3J7",
        "post_latitude": "50.4050",
        "post_longitude": "-105.5340",
        "phone": "306-692-8325",
        "email": "",
        "website": "https://www.facebook.com/thundercreekarchery/",
        "post_content": "Thunder Creek Archery Club is a community archery club located in the Town 'N' Country Mall in Moose Jaw, Saskatchewan. They host indoor shooting sessions and are affiliated with the Saskatchewan Archery Association.",
        "post_tags": "indoor, target",
        "business_hours": "",
        "facility_type": "Indoor",
        "has_pro_shop": "No",
        "has_3d_course": "No",
        "has_field_course": "No",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "No",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Timberland Bow Benders",
        "post_category": "Archery Club",
        "post_address": "Central Avenue North",
        "post_city": "Prince Albert",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "53.2033",
        "post_longitude": "-105.7531",
        "phone": "",
        "email": "",
        "website": "http://timberlandbowbenders.ca/wordpress/",
        "post_content": "Timberland Bow Benders is an archery club based in Prince Albert, Saskatchewan, operating out of the Prince Albert Wildlife Federation grounds on Central Avenue North. The club offers programs and range access for archers of all levels.",
        "post_tags": "outdoor, target",
        "business_hours": "",
        "facility_type": "Outdoor",
        "has_pro_shop": "No",
        "has_3d_course": "No",
        "has_field_course": "No",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "No",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Estevan Archery Club",
        "post_category": "Archery Club",
        "post_address": "Highway 47 South",
        "post_city": "Estevan",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "49.1392",
        "post_longitude": "-102.9861",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/EstevanArcheryClub/",
        "post_content": "Estevan Archery Club offers both indoor and outdoor archery facilities south of Estevan on Highway 47. The outdoor range extends west on Highway 18 towards the boundary dams. The club is affiliated with the Saskatchewan Archery Association.",
        "post_tags": "indoor, outdoor, target",
        "business_hours": "",
        "facility_type": "Both",
        "has_pro_shop": "No",
        "has_3d_course": "No",
        "has_field_course": "No",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "No",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Swift Current Archery Club",
        "post_category": "Archery Club",
        "post_address": "Colonel Clifton Centre",
        "post_city": "Swift Current",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "50.2881",
        "post_longitude": "-107.7939",
        "phone": "306-741-0045",
        "email": "",
        "website": "https://www.facebook.com/SwiftCurrentArcheryClub/",
        "post_content": "Swift Current Archery Club holds shooting sessions at the Colonel Clifton Centre in Swift Current, Saskatchewan. The club is affiliated with the Saskatchewan Archery Association and welcomes archers of all skill levels.",
        "post_tags": "indoor, target",
        "business_hours": "",
        "facility_type": "Indoor",
        "has_pro_shop": "No",
        "has_3d_course": "No",
        "has_field_course": "No",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "No",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Lloydminster & Area Archers",
        "post_category": "Archery Club",
        "post_address": "Hwy 303 East, Range Road 3265",
        "post_city": "Lloydminster",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "53.2932",
        "post_longitude": "-109.7697",
        "phone": "",
        "email": "membership.lloydarchers@gmail.com",
        "website": "https://lloydarchers.ca/",
        "post_content": "Lloydminster & Area Archers operates a versatile facility 15 km east of Lloydminster at the Lloydminster Fish & Game Youth Center. The heated, well-lit indoor range accommodates up to 18 archers at distances up to 40 yards. Outdoor facilities include a FITA range (10-50m) and a Field & 3D course.",
        "post_tags": "indoor, outdoor, 3D, field, FITA",
        "business_hours": "Tuesdays & Thursdays 7-9PM",
        "number_of_lanes": "18",
        "range_length_yards": "40",
        "facility_type": "Both",
        "has_pro_shop": "No",
        "has_3d_course": "Yes",
        "has_field_course": "Yes",
        "membership_required": "Yes",
        "equipment_rental_available": "No",
        "lessons_available": "Yes",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "No.1 Archery & Sports",
        "post_category": "Archery Range",
        "post_address": "Highway 1 East",
        "post_city": "Sherwood No. 159",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "50.4500",
        "post_longitude": "-104.5000",
        "phone": "306-352-9055",
        "email": "",
        "website": "https://no1archeryandsports.com/",
        "post_content": "No.1 Archery & Sports is a commercial indoor archery range and pro shop established in 1966, located approximately 10 km east of Regina on Highway 1 East. They distribute archery supplies and offer an automated indoor shooting range.",
        "post_tags": "indoor, pro shop, retail",
        "business_hours": "",
        "facility_type": "Indoor",
        "has_pro_shop": "Yes",
        "has_3d_course": "No",
        "has_field_course": "No",
        "membership_required": "No",
        "equipment_rental_available": "Yes",
        "lessons_available": "No",
        "bow_types_allowed": "Recurve, Compound, Longbow",
    },
    {
        "post_title": "Antler River Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Carievale",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "49.0833",
        "post_longitude": "-101.7833",
        "phone": "",
        "email": "",
        "website": "",
        "post_content": "Antler River Archery Club is a community archery club based in Carievale, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Apple Shot Archers Inc",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Macoun",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "49.2667",
        "post_longitude": "-102.8000",
        "phone": "",
        "email": "",
        "website": "http://appleshotarchers.ca",
        "post_content": "Apple Shot Archers Inc is an archery club based in Macoun, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Assiniboine River Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Canora",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "51.6333",
        "post_longitude": "-102.4333",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/arac.canora/",
        "post_content": "Assiniboine River Archery Club is a community archery club based in Canora, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Bad to the Bow Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Leoville",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "53.5167",
        "post_longitude": "-107.4667",
        "phone": "",
        "email": "",
        "website": "",
        "post_content": "Bad to the Bow Archery Club is a community archery club based in Leoville, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Beaver River Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Meadow Lake",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "54.1283",
        "post_longitude": "-108.4344",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/people/Beaver-River-Archery-Club/100069751191023/",
        "post_content": "Beaver River Archery Club is a community archery club in Meadow Lake, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Broken Arrow Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Yorkton",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "51.2139",
        "post_longitude": "-102.4628",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/people/Broken-Arrow-Archery-Club-Yorkton/100064392023358/",
        "post_content": "Broken Arrow Archery Club is a community archery club based in Yorkton, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "indoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Bruno Bowmen",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Bruno",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "52.2667",
        "post_longitude": "-105.3333",
        "phone": "",
        "email": "",
        "website": "https://facebook.com/profile.php?id=61555188276645",
        "post_content": "Bruno Bowmen is a community archery club based in Bruno, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Cypress Hills Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Maple Creek",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "49.9167",
        "post_longitude": "-109.4833",
        "phone": "",
        "email": "",
        "website": "",
        "post_content": "Cypress Hills Archery Club is a community archery club based in Maple Creek, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Fleming Archery",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Moosomin",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "50.1417",
        "post_longitude": "-101.6667",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/FlemingArcheryClub/",
        "post_content": "Fleming Archery is a community archery club based in the Moosomin area of Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Langenburg Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Langenburg",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "50.8500",
        "post_longitude": "-101.7167",
        "phone": "",
        "email": "",
        "website": "",
        "post_content": "Langenburg Archery Club is a community archery club based in Langenburg, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Moose Creek Archers",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Oxbow",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "49.2333",
        "post_longitude": "-102.1667",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/groups/285156531609719/",
        "post_content": "Moose Creek Archers is a community archery club based in Oxbow, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Prairie to Pines Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Sturgis",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "51.9417",
        "post_longitude": "-102.5500",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/SturgisArcheryClub/",
        "post_content": "Prairie to Pines Archery Club is a community archery club in the Sturgis area of Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "River Valley Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Veregin",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "51.6500",
        "post_longitude": "-102.0667",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/groups/177030792913732/",
        "post_content": "River Valley Archery Club is a community archery club based in Veregin, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Spiritwood Spirited Arrows",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Spiritwood",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "53.3667",
        "post_longitude": "-107.5000",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/groups/241250679360971/",
        "post_content": "Spiritwood Spirited Arrows is a community archery club based in Spiritwood, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Tru Flite Archery",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Melville",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "50.9333",
        "post_longitude": "-102.8000",
        "phone": "",
        "email": "",
        "website": "",
        "post_content": "Tru Flite Archery is a community archery club based in Melville, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Valley Arrowheads Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Osler",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "52.3833",
        "post_longitude": "-106.5333",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/valleyarrowheadsac/",
        "post_content": "Valley Arrowheads Archery Club is a community archery club based in Osler, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
    {
        "post_title": "Viscount Archery Club",
        "post_category": "Archery Club",
        "post_address": "",
        "post_city": "Viscount",
        "post_region": "Saskatchewan",
        "post_country": "Canada",
        "post_zip": "",
        "post_latitude": "51.9167",
        "post_longitude": "-105.6500",
        "phone": "",
        "email": "",
        "website": "https://www.facebook.com/profile.php?id=100063753841960",
        "post_content": "Viscount Archery Club is a community archery club based in Viscount, Saskatchewan, affiliated with the Saskatchewan Archery Association.",
        "post_tags": "outdoor",
        "business_hours": "",
        "facility_type": "",
        "has_pro_shop": "No",
        "has_3d_course": "",
        "has_field_course": "",
        "membership_required": "Yes",
        "equipment_rental_available": "",
        "lessons_available": "",
        "bow_types_allowed": "",
    },
]

# CSV columns matching the required format
CSV_COLUMNS = [
    "post_title", "post_author", "post_category", "F174",
    "post_address", "post_city", "post_region", "post_country",
    "post_zip", "post_latitude", "post_longitude", "phone", "email",
    "website", "post_content", "post_tags", "business_hours",
    "post_images", "range_length_yards", "number_of_lanes",
    "facility_type", "has_pro_shop", "has_3d_course", "has_field_course",
    "membership_required", "membership_price_adult", "drop_in_price",
    "equipment_rental_available", "lessons_available", "lesson_price_range",
    "bow_types_allowed", "accessibility", "parking_available"
]


async def crawl_club_website(crawler, url, club_name):
    """Use crawl4ai to crawl a club website and extract text content."""
    if not url or "facebook.com" in url:
        return None  # Skip Facebook pages (requires login)
    
    try:
        config = CrawlerRunConfig(
            word_count_threshold=10,
            exclude_external_links=True,
        )
        result = await crawler.arun(url=url, config=config)
        if result.success:
            print(f"  ✓ Crawled {club_name}: {len(result.markdown or '')} chars")
            return result.markdown
        else:
            print(f"  ✗ Failed to crawl {club_name}: {result.error_message}")
            return None
    except Exception as e:
        print(f"  ✗ Error crawling {club_name}: {e}")
        return None


async def main():
    """Main scraping function."""
    output_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "saskatchewan_ranges.csv"
    )

    print("=" * 60)
    print("Saskatchewan Archery Ranges Scraper (crawl4ai)")
    print("=" * 60)
    print(f"\nTotal clubs to process: {len(CLUBS)}")
    print(f"Output: {output_path}\n")

    # Crawl club websites to enrich data
    browser_config = BrowserConfig(
        headless=True,
        browser_type="chromium",
    )

    # Gather extra data from website crawls
    async with AsyncWebCrawler(config=browser_config) as crawler:
        for club in CLUBS:
            url = club.get("website", "")
            name = club["post_title"]
            if url and "facebook.com" not in url:
                print(f"Crawling: {name} ({url})")
                content = await crawl_club_website(crawler, url, name)
                if content:
                    # Store crawled content for reference
                    club["_crawled"] = content[:2000]  # Keep first 2000 chars
            else:
                print(f"Skipping (no crawlable URL): {name}")

    # Write CSV
    print(f"\nWriting {len(CLUBS)} ranges to CSV...")
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        writer.writeheader()

        for club in CLUBS:
            row = {}
            for col in CSV_COLUMNS:
                if col == "post_author":
                    row[col] = "Admin"
                elif col == "F174":
                    row[col] = ""
                elif col == "post_images":
                    row[col] = ""
                elif col == "accessibility":
                    row[col] = ""
                elif col == "parking_available":
                    row[col] = ""
                else:
                    row[col] = club.get(col, "")
            writer.writerow(row)

    print(f"\n✅ Done! {len(CLUBS)} Saskatchewan archery ranges saved to:")
    print(f"   {output_path}")


if __name__ == "__main__":
    asyncio.run(main())
